### ISSUE TITLE
Request single commission number

### ISSUE THREAD

**Issue by bagges** [SushiTee/vwkommi#2]
Would be nice to have the feature to request a single commission number with -s or something. Maybe also with username(-u) and password(-p) as parameter of vwcommi. Would make the settings_local.py for this call superfluous. What do you mean?

**Comment by SushiTee** [comment]
Yeah, I plan to make all options of the settings_local accessable by command line parameters.

**Comment by SushiTee** [comment]
fixed by 3c44604435765373094f8926b20cec36c177dc01

You can now request a single commission number like so:

```
python -m vwkommi request -c '[[\"AH\",1234,1234,4]]'
```

This will request the commission number AH1234.

The format is a bit tricy and may vary depending on the OS. I recommend to not include any spaces. The last number there is the length of the number part of the commission number. E.g. if the commission number would be ADC053. The parameter would look like this: '[[\"ADC\",53,53,3]]'
